#!/bin/bash
# ============================================================
# Script 5 : OSS Philosophy Creator
# Author   : VRAJ J. PATEL
# Reg. No. : 24BCE11378
# Slot     : D11
# Submitted: 31/03/2026
# Course   : Open Source Software
# ============================================================

echo "========================================="
echo "        OSS PHILOSOPHY CREATOR"
echo "========================================="
echo "This script creates a personal open-source manifesto."
echo "-----------------------------------------"

read -p "Which open-source software do you use daily? " TOOL
read -p "What does software freedom mean to you? " FREEDOM
read -p "What would you build and share with the world? " BUILD
read -p "Which open-source license would you choose? " LICENSE

DATE=$(date "+%d/%m/%Y %H:%M:%S")
AUTHOR_USER=$(whoami | tr '\\' '_')
FILE="oss_manifesto_${AUTHOR_USER}.txt"

{
    echo "-----------------------------------------"
    echo "        OPEN SOURCE PHILOSOPHY"
    echo "-----------------------------------------"
    echo "Generated by : VRAJ J. PATEL (24BCE11378)"
    echo "Generated on : $DATE"
    echo "Slot         : D11"
    echo ""
    echo "I use $TOOL regularly and it shows the power of open-source software."
    echo "To me, software freedom means $FREEDOM."
    echo "In the future, I would like to build $BUILD and share it with everyone."
    echo "I believe in the principles of the $LICENSE license."
    echo "-----------------------------------------"
    echo "Open-source software empowers individuals and communities alike."
    echo "-----------------------------------------"
} > "$FILE"

echo ""
echo "Manifesto saved to: $FILE"
echo "-----------------------------------------"
cat "$FILE"

echo "-----------------------------------------"
echo "Student : VRAJ J. PATEL  |  Reg: 24BCE11378  |  Slot: D11"
echo "========================================="
